* Install =OpenBSD=

** Create bootable USB install media

*** Erase install media partition

Before burning the install media file to the USB, you better to destroy the existing USB partitions.

**** MacOS

If you're using =MacOS=, plug the USB in and run =diskutil disk= to list your USB device:

#+BEGIN_SRC bash
  diskutil list 

  #
  # ... Ignore the internal SSD
  #

  # /dev/disk5 (external, physical):
  #    #:                       TYPE NAME       SIZE       IDENTIFIER
  #    0:      GUID_partition_scheme           *30.8 GB    disk5
  #    1:                        EFI EFI        209.7 MB   disk5s1
  #    2:       Microsoft Basic Data OPENBSD    30.4 GB    disk5s2
  #                     (free space)            135.2 MB   -
#+END_SRC

So, the =/dev/disk5= is your USB. Run the following command to erase the existing partitions:

#+BEGIN_SRC bash
  #
  # You have to unmount it first, otherwise, you're not
  # allowed to overwrite it.
  #
  sudo diskutil unmountDisk /dev/disk5

  #
  # Now, erase the existing partitions
  # allowed to overwrite it.
  #
  sudo dd if=/dev/zero of=/dev/disk5 bs=512 count=1
#+END_SRC

If you run =diskutil list= again, you should see this:

#+BEGIN_SRC bash
  /dev/disk5 (external, physical):
     #:                       TYPE NAME                    SIZE       IDENTIFIER
     0:                                                   *30.8 GB    disk5
#+END_SRC

So, that means the existing partitions are gone.


**** FreeBSD

#+BEGIN_SRC bash
  lsblk

  # DEVICE         MAJ:MIN SIZE TYPE                                    LABEL MOUNT
  # da0              1:188  29G MBR                                         - -
  #   <FREE>         -:-   512B -                                           - -
  #   da0s1          1:189 480K efi                                         - -
  #   da0s4          1:190 664M !166                                        - -
  #   <FREE>         -:-    28G -                                           - -
#+END_SRC

So, the =/dev/da0= is your USB, run the following command to erase the existing partitions:

#+BEGIN_SRC bash
  doas dd if=/dev/zero of=/dev/da0 bs=512 count=1 
#+END_SRC


*** Download IMG file and write to USB

Find your mirror from [[https://www.openbsd.org/ftp.html][here]] and download the =install74.img=.

For installing OpenBSD on Apple M1/M2 architecture, you should download =ARM64=!!!

After that, write the IMG file to USB:

#+BEGIN_SRC bash
  #
  # MacOS
  #
  sudo dd if=$HOME/Downloads/install74.img of=/dev/disk5 bs=1M

  #
  # FreeBSD
  #
  doas dd if=$HOME/Downloads/install74.img of=/dev/da0 bs=1M
#+END_SRC


** If you're installing OpenBSD on Appple M1/M2

Follow this video to install =Asahi Linux Installer= and make sure choose =UEFI= only and then reboot and choose =OpenBSD USB= to boot.




** Install sets from USB

When it asks =Which disk is the root disk=, you can press =?= to list all the physical disks in your computer, then markdown the =USB= install media one (e.g. =sd1=).

When asking =Location of sets?=, type =disk=.

When asking =Is the disk partition already mounted?= type =no=

When asking =Which disk contains the install media?= type =sd1= (the disk name you markdown before)

So you should be able to install sets via =disk=:)

